2025-02-22 19:15:02,817 INFO    MainThread:59004 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-22 19:15:02,817 INFO    MainThread:59004 [wandb_setup.py:_flush():67] Configure stats pid to 59004
2025-02-22 19:15:02,817 INFO    MainThread:59004 [wandb_setup.py:_flush():67] Loading settings from /home/nganvu/.config/wandb/settings
2025-02-22 19:15:02,817 INFO    MainThread:59004 [wandb_setup.py:_flush():67] Loading settings from /home/nganvu/nd0821-c2-build-model-workflow-exercises/lesson-1-machine-learning-pipelines/exercises/exercise_1/solution/wandb/settings
2025-02-22 19:15:02,817 INFO    MainThread:59004 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-22 19:15:02,817 INFO    MainThread:59004 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/nganvu/nd0821-c2-build-model-workflow-exercises/lesson-1-machine-learning-pipelines/exercises/exercise_1/solution/wandb/run-20250222_191502-kne0hvz8/logs/debug.log
2025-02-22 19:15:02,817 INFO    MainThread:59004 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/nganvu/nd0821-c2-build-model-workflow-exercises/lesson-1-machine-learning-pipelines/exercises/exercise_1/solution/wandb/run-20250222_191502-kne0hvz8/logs/debug-internal.log
2025-02-22 19:15:02,817 INFO    MainThread:59004 [wandb_init.py:init():761] calling init triggers
2025-02-22 19:15:02,817 INFO    MainThread:59004 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-02-22 19:15:02,817 INFO    MainThread:59004 [wandb_init.py:init():784] starting backend
2025-02-22 19:15:02,817 INFO    MainThread:59004 [wandb_init.py:init():788] sending inform_init request
2025-02-22 19:15:02,840 INFO    MainThread:59004 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-02-22 19:15:02,840 INFO    MainThread:59004 [wandb_init.py:init():803] backend started and connected
2025-02-22 19:15:02,841 INFO    MainThread:59004 [wandb_init.py:init():896] updated telemetry
2025-02-22 19:15:02,845 INFO    MainThread:59004 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-02-22 19:15:03,286 INFO    MainThread:59004 [wandb_init.py:init():995] starting run threads in backend
2025-02-22 19:15:03,352 INFO    MainThread:59004 [wandb_run.py:_console_start():2377] atexit reg
2025-02-22 19:15:03,352 INFO    MainThread:59004 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-02-22 19:15:03,352 INFO    MainThread:59004 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-02-22 19:15:03,353 INFO    MainThread:59004 [wandb_run.py:_redirect():2317] Redirects installed.
2025-02-22 19:15:03,354 INFO    MainThread:59004 [wandb_init.py:init():1037] run started, returning control to user process
2025-02-22 19:15:04,458 WARNING MsgRouterThr:59004 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/nganvu/miniconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/home/nganvu/miniconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/nganvu/miniconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nganvu/miniconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/home/nganvu/miniconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-02-22 19:15:04,458 INFO    MsgRouterThr:59004 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
